RECIPE_INGREDIENT_AMOUNT_MIN = 1
RECIPE_INGREDIENT_AMOUNT_MAX = 32000
RECIPE_INGREDIENT_COOKING_TIME_MIN = 1
RECIPE_INGREDIENT_COOKING_TIME_MAX = 32000
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 100
INGREDIENT_NAME_MAX_LENGTH = 50
