# Generated by Django 3.2 on 2024-12-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.TextField(choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', verbose_name='Пользовательская роль'),
        ),
    ]
